//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessClubUstinovAlecsandr.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int IDClient { get; set; }
        public string Name { get; set; }
        public string patronymic { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string PassportSeries { get; set; }
        public string PassportNumber { get; set; }
        public int Genger { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual Order Order { get; set; }
    }
}
