//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitnessClubUstinovAlecsandr.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainer
    {
        public int IDTrainer { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public string WorkingHours { get; set; }
        public string WorkExperience { get; set; }
    }
}
